#ifdef CH_LANG_CC
/*
 * Indexing for the rate and state IBC
 */
#endif


#ifndef _RSINDEX_H_
#define _RSINDEX_H_
#include "BaseNamespaceHeader.H"

#define RX_VX          ( 0)
#define RX_VZ          ( 1)
#define RX_V           ( 2)
#define RX_SXY         ( 3)
#define RX_SYZ         ( 4)
#define RX_SYY         ( 5)
#define RX_DX          ( 6)
#define RX_DZ          ( 7)
#define RX_DT          ( 8)
#define RX_RT          ( 9)
#define RX_PSI         (10)

#include "BaseNamespaceFooter.H"
#endif /*_RSINDEX_H_*/
